import Head from "next/head";
import Header from "../components/Header";
import Banner from "../components/Header";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Airbnb</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
    </div>
  );
}
